"""add_fk_indexes

Revision ID: 0e37d034f0bd
Revises: ba7e64d6740c
Create Date: 2026-06-02 11:47:32.552526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e37d034f0bd'
down_revision: Union[str, Sequence[str], None] = 'ba7e64d6740c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faces', 'image_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_faces_image_id'), 'faces', ['image_id'], unique=False)
    op.drop_constraint(op.f('faces_image_id_fkey'), 'faces', type_='foreignkey')
    op.create_foreign_key(None, 'faces', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.alter_column('images', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_images_project_id'), 'images', ['project_id'], unique=False)
    op.drop_constraint(op.f('images_project_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_project_id_fkey'), 'images', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_images_project_id'), table_name='images')
    op.alter_column('images', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'faces', type_='foreignkey')
    op.create_foreign_key(op.f('faces_image_id_fkey'), 'faces', 'images', ['image_id'], ['id'])
    op.drop_index(op.f('ix_faces_image_id'), table_name='faces')
    op.alter_column('faces', 'image_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
